### PR TITLE
Move to Interpolations.jl

### LINKED ISSUE #43: Switch from Dierckx.jl to Interpolations.jl
`Dierckx` does not preserve type https://github.com/kbarbary/Dierckx.jl/issues/48 and it is not GPU compatible. It also has some loading costs that can be avoided.

### PR DESCRIPTION
**Pull request by Sbozzolo**
Note that the order of interpolation is now first instead of cubic.

Is this acceptable?

Closes #43 
Closes #39

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Hmm, the docs are breaking, and the tests have all sorts of issues. Maybe we can fix the tests first.

**Comment by Sbozzolo** [comment]
> Hmm, the docs are breaking, and the tests have all sorts of issues. Maybe we can fix the tests first.

What issues do you see in tests? Aren't they all passing?

**Comment by charleskawczynski** [comment]
> What issues do you see in tests? Aren't they all passing?

Sorry, I meant that the design of the tests in this repo need improvement-- Right now, the things that are tested are implicit, based on `names(AtmosphericProfilesLibrary; all = true)` / `getproperty(AtmosphericProfilesLibrary, name)` of those names, which requires ignoring/skipping names-- it's way more complicated than it needs to be. Also, the inference tests are just wrong (`@test @inferred Float32 iscallable(prof(Float32))`).

**Comment by charleskawczynski** [comment]
I think https://github.com/CliMA/AtmosphericProfilesLibrary.jl/pull/45 fixes all of this.

**Comment by charleskawczynski** [comment]
Sorry about all the conflicts, I can rebase if you'd like

**Comment by charleskawczynski** [comment]
Rebased

**Review by charleskawczynski — APPROVED** [review]
Results in the docs look visually indistinguishable.

**Pull request merged**
